# Generated by Django 3.1.4 on 2020-12-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_annotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicom',
            name='is_labeled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dicom',
            name='picture',
            field=models.ImageField(default='C:/Users/patry/Documents/STUDIA/SEM_VII/PRZETWARZANIE/projekt/DICOM-Annotator-server/media/glowa.dcm', max_length=255, upload_to='uploads/'),
        ),
    ]
