# Generated by Django 3.1.4 on 2020-12-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_annotator', '0003_auto_20201203_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('is_labeled', models.BooleanField(default=False)),
                ('picture', models.ImageField(default='media/uploads/glowa.png', max_length=255, upload_to='uploads/')),
            ],
        ),
    ]
