# Generated by Django 3.1.4 on 2020-12-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_annotator', '0004_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='picture',
            field=models.FileField(default='media/glowa.dcm', max_length=255, upload_to='uploads/'),
        ),
    ]
