# Generated by Django 3.1.4 on 2020-12-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_annotator', '0005_auto_20201204_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PNG',
        ),
        migrations.AlterField(
            model_name='dicom',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
