# Generated by Django 3.1.4 on 2020-12-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_annotator', '0006_auto_20201204_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicom',
            name='labeled_picture',
            field=models.FileField(default='', max_length=255, upload_to='labeled/'),
        ),
        migrations.AlterField(
            model_name='dicom',
            name='picture',
            field=models.FileField(default='', max_length=255, upload_to='uploads/'),
        ),
    ]
