# Generated by Django 3.1.4 on 2020-12-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_annotator', '0007_auto_20201212_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicom',
            name='labeled_picture',
        ),
    ]
